import "./globals.css";
import { Inter } from "next/font/google";
import { ToastContainer} from 'react-toastify';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hotel Management App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} m-0 p-0 bg-slate-100`}>
        <ToastContainer/>
        {children}
      </body>
    </html>
  );
}